[project]
name = "aoc-2025"
version = "0.1.0"
description = "Advent of Code 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adventofcode>=25.7",
    "contexttimer>=0.3.3",
    "numpy>=2.3.5",
    "pytest>=9.0.1",
]
